<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSxbTQD7\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSxbTQD7/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSxbTQD7.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSxbTQD7\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSxbTQD7\App_KernelDevDebugContainer([
    'container.build_hash' => 'SxbTQD7',
    'container.build_id' => '512d8676',
    'container.build_time' => 1648751610,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSxbTQD7');
