<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBD7qYRw\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBD7qYRw/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBD7qYRw.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBD7qYRw\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBD7qYRw\App_KernelDevDebugContainer([
    'container.build_hash' => 'BD7qYRw',
    'container.build_id' => '6532309f',
    'container.build_time' => 1646081916,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBD7qYRw');
