<?php

namespace ContainerMEcEJQJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSubuser2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.SWF0qEr.App\Entity\Subuser' shared service.
     *
     * @return \App\Entity\Subuser
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.SWF0qEr": it references class "App\\Entity\\Subuser" but no such service exists.');
    }
}
