<?php

namespace ContainerZMtIr2y;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Rdnugh2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rdnugh2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rdnugh2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['privates', '.errored.dsqNfxx', NULL, 'Cannot determine controller argument for "App\\Controller\\UserCrudController::delete()": the $entityManager argument is type-hinted with the non-existent class or interface: "App\\Controller\\EntityManagerInterface". Did you forget to add a use statement?'],
            'user' => ['privates', '.errored..service_locator.rdnugh2.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.rdnugh2": it references class "App\\Entity\\User" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'user' => 'App\\Entity\\User',
        ]);
    }
}
