<?php

namespace ContainerKZ6cmHx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PPsXs3mService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pPsXs3m' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pPsXs3m'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'subuserRepository' => ['privates', 'App\\Repository\\SubuserRepository', 'getSubuserRepositoryService', true],
        ], [
            'subuserRepository' => 'App\\Repository\\SubuserRepository',
        ]);
    }
}
