<?php

namespace ContainerJgW2Ldc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getKnpMenu_Renderer_ListService extends App_KernelProdContainer
{
    /*
     * Gets the private 'knp_menu.renderer.list' shared service.
     *
     * @return \Knp\Menu\Renderer\ListRenderer
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['knp_menu.renderer.list'] = new \Knp\Menu\Renderer\ListRenderer(($container->services['knp_menu.matcher'] ?? $container->load('getKnpMenu_MatcherService')), [], 'UTF-8');
    }
}
