<?php

namespace ContainerJgW2Ldc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getKnpMenu_MatcherService extends App_KernelProdContainer
{
    /*
     * Gets the public 'knp_menu.matcher' shared service.
     *
     * @return \Knp\Menu\Matcher\Matcher
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['knp_menu.matcher'] = new \Knp\Menu\Matcher\Matcher(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['knp_menu.voter.router'] ?? $container->load('getKnpMenu_Voter_RouterService'));
        }, 1));
    }
}
