<?php

namespace ContainerJgW2Ldc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getKnpMenu_Renderer_TwigService extends App_KernelProdContainer
{
    /*
     * Gets the private 'knp_menu.renderer.twig' shared service.
     *
     * @return \Knp\Menu\Renderer\TwigRenderer
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['knp_menu.renderer.twig'] = new \Knp\Menu\Renderer\TwigRenderer(($container->services['.container.private.twig'] ?? $container->load('get_Container_Private_TwigService')), 'KnpMenuBundle::menu.html.twig', ($container->services['knp_menu.matcher'] ?? $container->load('getKnpMenu_MatcherService')), []);
    }
}
