<?php

namespace ContainerJgW2Ldc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMovieRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\MovieRepository' shared autowired service.
     *
     * @return \App\Repository\MovieRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\MovieRepository'] = new \App\Repository\MovieRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
