<?php

namespace ContainerJgW2Ldc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getQuoteRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\QuoteRepository' shared autowired service.
     *
     * @return \App\Repository\QuoteRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\QuoteRepository'] = new \App\Repository\QuoteRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
