<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJgW2Ldc\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJgW2Ldc/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerJgW2Ldc.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerJgW2Ldc\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerJgW2Ldc\App_KernelProdContainer([
    'container.build_hash' => 'JgW2Ldc',
    'container.build_id' => '05d67cfe',
    'container.build_time' => 1643658559,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJgW2Ldc');
