<?php

namespace ContainerW7jaunn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0nD7sF6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0nD7sF6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0nD7sF6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'doctrine' => ['privates', '.errored..service_locator.0nD7sF6.Symfony\\Bridge\\Doctrine\\ManagerRegistry', NULL, 'Cannot autowire service ".service_locator.0nD7sF6": it references class "Symfony\\Bridge\\Doctrine\\ManagerRegistry" but no such service exists. Try changing the type-hint to "Doctrine\\Persistence\\ManagerRegistry" instead.'],
        ], [
            'doctrine' => 'Symfony\\Bridge\\Doctrine\\ManagerRegistry',
        ]);
    }
}
