<?php

namespace ContainerW7jaunn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getManagerRegistryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.0nD7sF6.Symfony\Bridge\Doctrine\ManagerRegistry' shared service.
     *
     * @return \Symfony\Bridge\Doctrine\ManagerRegistry
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.0nD7sF6": it references class "Symfony\\Bridge\\Doctrine\\ManagerRegistry" but no such service exists. Try changing the type-hint to "Doctrine\\Persistence\\ManagerRegistry" instead.');
    }
}
