<?php

namespace ContainerXKSDIax;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SWF0qErService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SWF0qEr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SWF0qEr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'subuser' => ['privates', '.errored..service_locator.SWF0qEr.App\\Entity\\Subuser', NULL, 'Cannot autowire service ".service_locator.SWF0qEr": it references class "App\\Entity\\Subuser" but no such service exists.'],
        ], [
            'subuser' => 'App\\Entity\\Subuser',
        ]);
    }
}
