<?php

namespace ContainerWqRs44C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__VW11WJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..vW11WJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..vW11WJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['privates', '.errored.R0eb_O5', NULL, 'Cannot determine controller argument for "App\\Controller\\MovieCrudController::edit()": the $entityManager argument is type-hinted with the non-existent class or interface: "App\\Controller\\EntityManagerInterface". Did you forget to add a use statement?'],
            'movie' => ['privates', '.errored..service_locator..vW11WJ.App\\Entity\\Movie', NULL, 'Cannot autowire service ".service_locator..vW11WJ": it references class "App\\Entity\\Movie" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'movie' => 'App\\Entity\\Movie',
        ]);
    }
}
