<?php

namespace ContainerWqRs44C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMovieService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator..vW11WJ.App\Entity\Movie' shared service.
     *
     * @return \App\Entity\Movie
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator..vW11WJ": it references class "App\\Entity\\Movie" but no such service exists.');
    }
}
